name: Shell Commands 

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: echo a string 
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Branch environment
        run: |
          
          echo $GITHUB_REF
          
          [ "$GITHUB_REF" = "refs/heads/ci-job" ] && ENVS="develop"
          [ "$GITHUB_REF" = "refs/heads/master" ] && ENVS="homolog"
          [ "$GITHUB_REF" = "refs/heads/homolog" ] && ENVS="homolog"
          [ "$GITHUB_REF" = "refs/heads/production" ] && ENVS="production"
          
          echo $ENVS
          
          
          
          
          

