name: Shell Commands 

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: echo a string 
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Branch environment
        run: |
          
          echo $GITHUB_REF
          
          [ "$GITHUB_REF" = "refs/heads/ci-job" ] && { ENVS="develop"; echo $ENVS; }
          
          [ "$GITHUB_REF" = "refs/heads/master" ] && { ENVS="develop"; echo $ENVS; }
          
          [ "$GITHUB_REF" = "refs/heads/homolog" ] && { ENVS="homolog"; echo $ENVS; }
          
          [ "$GITHUB_REF" = "refs/heads/production" ] && { ENVS="production"; echo $ENVS; }
          
          
          
          
          

